# Generated by Django 5.2.4 on 2025-08-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fomes_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='order_date',
        ),
        migrations.AddField(
            model_name='home',
            name='floor',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='number',
            field=models.CharField(max_length=5),
        ),
    ]
