# Generated by Django 5.2.4 on 2025-10-10 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fomes_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='user',
            field=models.ForeignKey(help_text='The user that created the home', on_delete=django.db.models.deletion.CASCADE, related_name='homes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='home',
            field=models.ForeignKey(help_text='The home which the review is about', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fomes_api.home'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='The user that created the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
